-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES TABLE
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  role text check (role in ('admin', 'manager', 'member')) default 'member',
  full_name text,
  avatar_url text,
  created_at timestamptz default now()
);

-- Trigger to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'member');
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- PROJECTS TABLE
create table projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_by uuid references profiles(id),
  created_at timestamptz default now()
);

-- PROJECT MEMBERS TABLE (Many-to-Many)
create table project_members (
  project_id bigint references projects(id) on delete cascade,
  user_id uuid references profiles(id) on delete cascade,
  role text check (role in ('manager', 'member')) default 'member',
  joined_at timestamptz default now(),
  primary key (project_id, user_id)
);

-- TASKS TABLE
create table tasks (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  title text not null,
  description text,
  status text check (status in ('todo', 'in-progress', 'done')) default 'todo',
  deadline timestamptz,
  assigned_to uuid references profiles(id),
  created_at timestamptz default now()
);

-- SECURITY POLICIES (RLS)
alter table profiles enable row level security;
alter table projects enable row level security;
alter table project_members enable row level security;
alter table tasks enable row level security;

-- Profiles: Public read, Self update. Admin update all.
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );
  
-- Projects: Visible to members and admins.
create policy "Projects viewable by members"
  on projects for select
  using (
    auth.uid() in (select user_id from project_members where project_id = id)
    or
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "Managers and Admins can create projects"
  on projects for insert
  with check (
    exists (select 1 from profiles where id = auth.uid() and role in ('admin', 'manager'))
  );

-- Tasks: Visible to project members.
create policy "Tasks viewable by project members"
  on tasks for select
  using (
    exists (select 1 from project_members where project_id = tasks.project_id and user_id = auth.uid())
    or
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "Members can update tasks assigned to them"
  on tasks for update
  using (
    assigned_to = auth.uid() 
    or 
    exists (select 1 from project_members where project_id = tasks.project_id and user_id = auth.uid() and role = 'manager')
    or
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );
